// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYBumiU4BeQRzFofng8XKk6clwYmzXwc',
    appId: '1:103847336237:android:ee6578040374b80063dba4',
    messagingSenderId: '103847336237',
    projectId: 'karatahta-f1e79',
    storageBucket: 'karatahta-f1e79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC580q1G_fTd7qLrqRPt1ZceZGj7LUyUTI',
    appId: '1:103847336237:ios:bde08c753c738cff63dba4',
    messagingSenderId: '103847336237',
    projectId: 'karatahta-f1e79',
    storageBucket: 'karatahta-f1e79.firebasestorage.app',
    iosBundleId: 'com.example.karatahta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC580q1G_fTd7qLrqRPt1ZceZGj7LUyUTI',
    appId: '1:103847336237:ios:bde08c753c738cff63dba4',
    messagingSenderId: '103847336237',
    projectId: 'karatahta-f1e79',
    storageBucket: 'karatahta-f1e79.firebasestorage.app',
    iosBundleId: 'com.example.karatahta',
  );
}
